# Generated by Django 6.0.1 on 2026-01-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='courses/previews/', verbose_name='Превью')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена в рублях', max_digits=10, verbose_name='Цена курса')),
                ('stripe_product_id', models.CharField(blank=True, help_text='Автоматически создается при первой оплате', max_length=255, null=True, verbose_name='ID продукта Stripe')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Автоматически создается при первой оплате', max_length=255, null=True, verbose_name='ID цены Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lessons/previews/', verbose_name='Превью')),
                ('video_url', models.URLField(help_text='Только YouTube ссылки', verbose_name='Ссылка на видео')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена в рублях', max_digits=10, verbose_name='Цена урока')),
                ('stripe_product_id', models.CharField(blank=True, help_text='Автоматически создается при первой оплате', max_length=255, null=True, verbose_name='ID продукта Stripe')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Автоматически создается при первой оплате', max_length=255, null=True, verbose_name='ID цены Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
    ]
