# Generated by Django 6.0 on 2026-01-05 12:56

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, validators=[courses.validators.validate_youtube_url], verbose_name='Ссылка на видео'),
        ),
    ]
